version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - drf_network
    volumes:
      - drf_static:/data/static/
      - drf_media:/data/media/
      - drf_log:/var/log/nginx/

  django:
    image: drf_3:1.1
    networks:
      - drf_network
    volumes:
      - drf_static:/home/gis_drf_3/staticfiles/
      - drf_media:/home/gis_drf_3/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - drf_network
    volumes:
      - drf_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  drf_network:

configs:
  nginx_conf:
    external: true

volumes:
  drf_static:
  drf_media:
  drf_mariadb:
  drf_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true
